"""add claim management, programme, evidence integrity, and diary-project link

Revision ID: 0c083944653f
Revises: 9f6c1ee342cf
Create Date: 2026-07-30 16:22:41.922561

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0c083944653f'
down_revision: Union[str, Sequence[str], None] = '9f6c1ee342cf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('activities',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('activity_code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('planned_start', sa.Date(), nullable=False),
    sa.Column('planned_finish', sa.Date(), nullable=False),
    sa.Column('actual_start', sa.Date(), nullable=True),
    sa.Column('actual_finish', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('activity_predecessors',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('activity_id', sa.UUID(), nullable=False),
    sa.Column('predecessor_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['activity_id'], ['activities.id'], ),
    sa.ForeignKeyConstraint(['predecessor_id'], ['activities.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('event_activity_impacts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('event_id', sa.UUID(), nullable=False),
    sa.Column('activity_id', sa.UUID(), nullable=False),
    sa.Column('impact_days', sa.Integer(), nullable=False),
    sa.Column('risk_category', sa.String(length=20), nullable=False),
    sa.Column('notes', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['activity_id'], ['activities.id'], ),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('claims',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('claim_type', sa.String(length=20), nullable=False),
    sa.Column('claiming_party', sa.String(length=20), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=30), server_default='Notified', nullable=False),
    sa.Column('awareness_date', sa.Date(), nullable=False),
    sa.Column('notice_submitted_date', sa.Date(), nullable=True),
    sa.Column('notice_evidence_id', sa.UUID(), nullable=True),
    sa.Column('detailed_claim_submitted_date', sa.Date(), nullable=True),
    sa.Column('legal_basis_statement', sa.Text(), nullable=True),
    sa.Column('particulars', sa.Text(), nullable=True),
    sa.Column('claimed_days', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['notice_evidence_id'], ['evidence.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('diary_event_links',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('diary_id', sa.UUID(), nullable=False),
    sa.Column('event_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['diary_id'], ['daily_diaries.id'], ),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('evidence_access_log',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('evidence_id', sa.UUID(), nullable=False),
    sa.Column('action', sa.String(length=20), nullable=False),
    sa.Column('accessed_by_user_id', sa.UUID(), nullable=True),
    sa.Column('accessed_by_email', sa.String(length=255), nullable=True),
    sa.Column('accessed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['accessed_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['evidence_id'], ['evidence.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('claim_access_tokens',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('claim_id', sa.UUID(), nullable=False),
    sa.Column('token', sa.String(length=64), nullable=False),
    sa.Column('recipient_email', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['claim_id'], ['claims.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token')
    )
    op.create_table('claim_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('claim_id', sa.UUID(), nullable=False),
    sa.Column('event_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['claim_id'], ['claims.id'], ),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('claim_facts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('claim_id', sa.UUID(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('proposed_by_party', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), server_default='Proposed', nullable=False),
    sa.Column('agreed_days', sa.Integer(), nullable=True),
    sa.Column('response_comment', sa.Text(), nullable=True),
    sa.Column('responded_by', sa.String(length=255), nullable=True),
    sa.Column('responded_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['claim_id'], ['claims.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('claim_responses',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('claim_id', sa.UUID(), nullable=False),
    sa.Column('response_type', sa.String(length=30), nullable=False),
    sa.Column('response_date', sa.Date(), nullable=False),
    sa.Column('days_granted', sa.Integer(), nullable=True),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('responded_by', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['claim_id'], ['claims.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('claim_fact_evidence',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('fact_id', sa.UUID(), nullable=False),
    sa.Column('evidence_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['evidence_id'], ['evidence.id'], ),
    sa.ForeignKeyConstraint(['fact_id'], ['claim_facts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # project_id is added nullable first and backfilled from the diary's
    # existing event, then locked to NOT NULL - a straight nullable=False
    # add_column would fail outright against any database that already
    # has diary rows.
    op.add_column('daily_diaries', sa.Column('project_id', sa.UUID(), nullable=True))
    op.execute(
        """
        UPDATE daily_diaries
        SET project_id = events.project_id
        FROM events
        WHERE daily_diaries.event_id = events.id
          AND daily_diaries.project_id IS NULL
        """
    )
    op.alter_column('daily_diaries', 'project_id', nullable=False)
    op.alter_column('daily_diaries', 'event_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.create_foreign_key(
        'fk_daily_diaries_project_id', 'daily_diaries', 'projects', ['project_id'], ['id']
    )
    op.add_column('evidence', sa.Column('sha256_hash', sa.String(length=64), nullable=True))
    op.add_column('evidence', sa.Column('is_locked', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('projects', sa.Column('notice_period_days', sa.Integer(), server_default='28', nullable=False))
    op.add_column('projects', sa.Column('detailed_claim_period_days', sa.Integer(), server_default='84', nullable=False))
    op.add_column('projects', sa.Column('engineer_late_notice_flag_days', sa.Integer(), server_default='14', nullable=False))
    op.add_column('projects', sa.Column('engineer_response_period_days', sa.Integer(), server_default='42', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('projects', 'engineer_response_period_days')
    op.drop_column('projects', 'engineer_late_notice_flag_days')
    op.drop_column('projects', 'detailed_claim_period_days')
    op.drop_column('projects', 'notice_period_days')
    op.drop_column('evidence', 'is_locked')
    op.drop_column('evidence', 'sha256_hash')
    op.drop_constraint('fk_daily_diaries_project_id', 'daily_diaries', type_='foreignkey')
    op.alter_column('daily_diaries', 'event_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_column('daily_diaries', 'project_id')
    op.drop_table('claim_fact_evidence')
    op.drop_table('claim_responses')
    op.drop_table('claim_facts')
    op.drop_table('claim_events')
    op.drop_table('claim_access_tokens')
    op.drop_table('evidence_access_log')
    op.drop_table('diary_event_links')
    op.drop_table('claims')
    op.drop_table('event_activity_impacts')
    op.drop_table('activity_predecessors')
    op.drop_table('activities')
    # ### end Alembic commands ###
