"""create daily diaries table

Revision ID: 8f45d989a415
Revises: 77a711aa31e6
Create Date: 2026-07-28 00:21:34.506871

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8f45d989a415'
down_revision: Union[str, Sequence[str], None] = '77a711aa31e6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('daily_diaries', sa.Column('diary_date', sa.Date(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('daily_diaries', 'diary_date')
    # ### end Alembic commands ###
