"""add notice_given_date to events

Revision ID: 9f6c1ee342cf
Revises: b8d7b7880eab
Create Date: 2026-07-30 13:24:24.510850

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9f6c1ee342cf'
down_revision: Union[str, Sequence[str], None] = 'b8d7b7880eab'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('notice_given_date', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('events', 'notice_given_date')
    # ### end Alembic commands ###
