"""create daily diaries table

Revision ID: a7c29767df10
Revises: b4471886ccc2
Create Date: 2026-07-27 10:43:39.421706

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a7c29767df10'
down_revision: Union[str, Sequence[str], None] = 'b4471886ccc2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('daily_diaries',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('event_id', sa.UUID(), nullable=False),
    sa.Column('work_completed', sa.Text(), nullable=True),
    sa.Column('manpower', sa.Integer(), nullable=True),
    sa.Column('equipment', sa.Text(), nullable=True),
    sa.Column('materials', sa.Text(), nullable=True),
    sa.Column('delays', sa.Text(), nullable=True),
    sa.Column('safety', sa.Text(), nullable=True),
    sa.Column('visitors', sa.Text(), nullable=True),
    sa.Column('engineer_instruction', sa.Text(), nullable=True),
    sa.Column('tomorrow_plan', sa.Text(), nullable=True),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('daily_diaries')
    # ### end Alembic commands ###
